apiVersion: v2
name: web-pentest-mcp
description: Web Penetration Testing MCP Server for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/your-org/web-pentest-mcp
sources:
  - https://github.com/your-org/web-pentest-mcp
maintainers:
  - name: Your Name
    email: your.email@example.com
keywords:
  - mcp
  - penetration-testing
  - security
  - web-security
  - kubernetes
annotations:
  category: Security
