{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web-pentest-mcp.fullname" . }}-config
  labels:
    {{- include "web-pentest-mcp.labels" . | nindent 4 }}
data:
  {{- if .Values.configMap.data }}
  {{- toYaml .Values.configMap.data | nindent 2 }}
  {{- end }}
  # MCP Server Configuration
  mcp-server-name: {{ .Values.mcp.serverName | quote }}
  mcp-transport: {{ .Values.mcp.transport | quote }}
  log-level: {{ .Values.mcp.logLevel | quote }}
  tool-timeout: {{ .Values.mcp.toolTimeout | quote }}
  
  # Security Tools Configuration
  nmap-config: |
    # Nmap configuration
    scan-timeout: 300
    max-retries: 3
    
  nikto-config: |
    # Nikto configuration
    scan-timeout: 180
    max-retries: 2
    
  sqlmap-config: |
    # SQLMap configuration
    scan-timeout: 300
    max-retries: 2
    
  wpscan-config: |
    # WPScan configuration
    scan-timeout: 240
    max-retries: 2
    
  dirb-config: |
    # Dirb configuration
    scan-timeout: 180
    max-retries: 2
    
  searchsploit-config: |
    # Searchsploit configuration
    scan-timeout: 60
    max-retries: 1
{{- end }}
