apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-pentest-mcp.fullname" . }}
  labels:
    {{- include "web-pentest-mcp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "web-pentest-mcp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "web-pentest-mcp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "web-pentest-mcp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
            {{- if .Values.monitoring.prometheus.enabled }}
            - name: metrics
              containerPort: {{ .Values.monitoring.prometheus.port }}
              protocol: TCP
            {{- end }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- range .Values.extraEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- if .Values.configMap.enabled }}
            - name: CONFIG_MAP_DATA
              valueFrom:
                configMapKeyRef:
                  name: {{ include "web-pentest-mcp.fullname" . }}-config
                  key: config.yaml
            {{- end }}
            {{- if .Values.secrets.enabled }}
            - name: SECRET_DATA
              valueFrom:
                secretKeyRef:
                  name: {{ include "web-pentest-mcp.fullname" . }}-secret
                  key: secret.yaml
            {{- end }}
          {{- if .Values.monitoring.healthCheck.enabled }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ .Values.monitoring.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.monitoring.healthCheck.periodSeconds }}
            timeoutSeconds: {{ .Values.monitoring.healthCheck.timeoutSeconds }}
            failureThreshold: {{ .Values.monitoring.healthCheck.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: {{ .Values.monitoring.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.monitoring.healthCheck.periodSeconds }}
            timeoutSeconds: {{ .Values.monitoring.healthCheck.timeoutSeconds }}
            failureThreshold: {{ .Values.monitoring.healthCheck.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /app/data
            {{- end }}
            {{- if .Values.configMap.enabled }}
            - name: config
              mountPath: /app/config
            {{- end }}
            {{- if .Values.secrets.enabled }}
            - name: secrets
              mountPath: /app/secrets
            {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "web-pentest-mcp.fullname" . }}-pvc
        {{- end }}
        {{- if .Values.configMap.enabled }}
        - name: config
          configMap:
            name: {{ include "web-pentest-mcp.fullname" . }}-config
        {{- end }}
        {{- if .Values.secrets.enabled }}
        - name: secrets
          secret:
            secretName: {{ include "web-pentest-mcp.fullname" . }}-secret
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
