{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "web-pentest-mcp.fullname" . }}-netpol
  labels:
    {{- include "web-pentest-mcp.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "web-pentest-mcp.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- else }}
  ingress:
    # Allow ingress from same namespace
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Release.Namespace }}
    # Allow ingress from ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
        - namespaceSelector:
            matchLabels:
              name: kube-system
    # Allow ingress from monitoring namespace if monitoring is enabled
    {{- if .Values.monitoring.prometheus.enabled }}
    - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
    {{- end }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- else }}
  egress:
    # Allow egress to DNS
    - to: []
      ports:
        - protocol: UDP
          port: 53
    # Allow egress to HTTP/HTTPS
    - to: []
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
    # Allow egress to common ports for security tools
    - to: []
      ports:
        - protocol: TCP
          port: 22    # SSH
        - protocol: TCP
          port: 3389  # RDP
        - protocol: TCP
          port: 5900  # VNC
        - protocol: TCP
          port: 8080  # Common web ports
        - protocol: TCP
          port: 8443  # HTTPS alternative
    # Allow egress to Kubernetes API server
    - to: []
      ports:
        - protocol: TCP
          port: 443
      to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
  {{- end }}
{{- end }}
