{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "web-pentest-mcp.fullname" . }}-role
  labels:
    {{- include "web-pentest-mcp.labels" . | nindent 4 }}
rules:
  # Allow reading ConfigMaps
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  
  # Allow reading Secrets
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  
  # Allow reading Pods for health checks
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  
  # Allow reading Services for discovery
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
  
  # Allow reading Endpoints for service discovery
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"]
  
  # Allow reading NetworkPolicies if enabled
  {{- if .Values.security.networkPolicy.enabled }}
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "watch"]
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "web-pentest-mcp.fullname" . }}-rolebinding
  labels:
    {{- include "web-pentest-mcp.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "web-pentest-mcp.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "web-pentest-mcp.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
