apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-pentest-mcp.fullname" . }}
  labels:
    {{- include "web-pentest-mcp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    {{- if .Values.monitoring.prometheus.enabled }}
    - port: {{ .Values.monitoring.prometheus.port }}
      targetPort: {{ .Values.monitoring.prometheus.port }}
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "web-pentest-mcp.selectorLabels" . | nindent 4 }}
